// Mocks generated by Mockito 5.3.2 from annotations
// in observador_app/test/domain/use_case/get_star_chart_image_use_case_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:observador_app/modules/astro/domain/model/body/body_details_model.dart'
    as _i3;
import 'package:observador_app/modules/astro/domain/model/body/body_list_data_model.dart'
    as _i4;
import 'package:observador_app/modules/astro/domain/model/body/body_model.dart'
    as _i8;
import 'package:observador_app/modules/astro/domain/model/image_url/image_data_model.dart'
    as _i2;
import 'package:observador_app/modules/astro/domain/model/moon_phase/moon_phase_model.dart'
    as _i7;
import 'package:observador_app/modules/astro/domain/model/star_chart/star_chart_model.dart'
    as _i9;
import 'package:observador_app/modules/astro/domain/repository/astro_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeImageDataModel_0 extends _i1.SmartFake
    implements _i2.ImageDataModel {
  _FakeImageDataModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBodyDetailsModel_1 extends _i1.SmartFake
    implements _i3.BodyDetailsModel {
  _FakeBodyDetailsModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBodyListDataModel_2 extends _i1.SmartFake
    implements _i4.BodyListDataModel {
  _FakeBodyListDataModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AstroRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAstroRepository extends _i1.Mock implements _i5.AstroRepository {
  MockAstroRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ImageDataModel> getMoonPhaseImage(
          _i7.MoonPhaseModel? moonPhaseModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMoonPhaseImage,
          [moonPhaseModel],
        ),
        returnValue: _i6.Future<_i2.ImageDataModel>.value(_FakeImageDataModel_0(
          this,
          Invocation.method(
            #getMoonPhaseImage,
            [moonPhaseModel],
          ),
        )),
      ) as _i6.Future<_i2.ImageDataModel>);
  @override
  _i6.Future<_i3.BodyDetailsModel> getBodyDetailsModel(
    _i8.BodyModel? bodyModel,
    String? bodyId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBodyDetailsModel,
          [
            bodyModel,
            bodyId,
          ],
        ),
        returnValue:
            _i6.Future<_i3.BodyDetailsModel>.value(_FakeBodyDetailsModel_1(
          this,
          Invocation.method(
            #getBodyDetailsModel,
            [
              bodyModel,
              bodyId,
            ],
          ),
        )),
      ) as _i6.Future<_i3.BodyDetailsModel>);
  @override
  _i6.Future<_i2.ImageDataModel> getStarChartImage(
          _i9.StarChartModel? starChartModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStarChartImage,
          [starChartModel],
        ),
        returnValue: _i6.Future<_i2.ImageDataModel>.value(_FakeImageDataModel_0(
          this,
          Invocation.method(
            #getStarChartImage,
            [starChartModel],
          ),
        )),
      ) as _i6.Future<_i2.ImageDataModel>);
  @override
  _i6.Future<_i4.BodyListDataModel> getBodyList() => (super.noSuchMethod(
        Invocation.method(
          #getBodyList,
          [],
        ),
        returnValue:
            _i6.Future<_i4.BodyListDataModel>.value(_FakeBodyListDataModel_2(
          this,
          Invocation.method(
            #getBodyList,
            [],
          ),
        )),
      ) as _i6.Future<_i4.BodyListDataModel>);
}
